### ISSUE TITLE
Issues with translation from email

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/TheOpenVoiceFactory#131]
Direct quote from email: 

> The download obz file link fails because the code has put a slash on the end! (For some reason this didn't turn up before now) If you remove the slash it works fine (I will do fix this bug very soon)
> The images, as you say, aren't appearing for images you've changed. This is pretty mysterious!
> 
> They aren't appearing in the OBF files https://designs.theopenvoicefactory.org/007c88a8ebc7d25615269220f61eead5/data/boards/chatting.obf either, so that suggests it's the python (my) code rather than the javascript player.  This is good because I can fix it more easily, but bad because it can't simply be put on OPTIKEY. 
>     But it's not causing the system to crash, it's still producing the files
>     I'm willing to bet the line that's causing the problem is this one:  https://github.com/eQualityTime/TheOpenVoiceFactory/blob/5206fee62e1b5da75d81ef6289d61d320c7601cd/grab_text.py#L521 - it's a cheap hack and I should have known better when I wrote it. What I suspect is happening is that Cyrilic characters are being ignored when naming a file, so it's being reduced more than it should, and that's causing an error later in the toolchain.  I can't check it on the system I'm using right now.

**Comment by joereddington-public** [comment]
Okay, let's do a Summary. 

A volenteer is doing a russian translation of Communikate so they can put it in Optikey. The translation has been sent over because they are having problems making it work. The problems are valid so I need to go though and fix them. 

# Plan 
- [ ] Upload the example file and get some proper informaiton about the issues 
- [ ] Fix the URL bug 
- [ ] Create a reduced version of the sample file to trigger the second bug. 
- [ ] Check out codebase 
- [ ] write tests that trigger the second bug
- [ ] get code to pass tests 
- [ ] push, pull, test

**Comment by joereddington-public** [comment]
Hmmm. Very strange thing that I need to work out - the version of OVf on server doesn't appear to be under git control? Issue with migration...

**Comment by joereddington** [comment]
[CK20V2_testing.pptx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/3922163/CK20V2_testing.pptx)

**Comment by joereddington** [comment]
Fixed very belatedly as part of the greek transation.
