### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by blaise17** [eQualityTime/TheOpenVoiceFactory#96]
Please write up the five aac users as personas and put the most obvious gotchas and questions and guidelines on cognitive load in an faq.

**Comment by joereddington-public** [comment]
So let's start drafting. 

Let's start with the three personas that I don't have to check for permission about...  OVF was built with Richard in mind - it is designed to support pre-literate users. The literate personas below are there for discussion and potential expansion. 

# Richard
Richard is in his mid-30s and has developmental difficulties. He has no speech, and limited cognitive ability (no reading and limited working memory.  His vision and hearing are fine. 

Richard will typically produce outputs of 1-3 symbols (occasionally four) that are presented without tense or indeed much context.  Examples might be <dad, sonic, screwdriver>.  This turns out NOT to be a Doctor Who reference.  Conversations with Richard require a lot of scaffolding: 

![screen shot 2018-08-28 at 12 15 32](https://user-images.githubusercontent.com/40637406/44719777-371cad80-aabc-11e8-88fc-784aa9de727b.png)

(From [this book chapter](http://joereddington.com/wp-content/uploads/2013/10/STAL9781614992950-0059_AC.pdf) which is particularly interesting on the topic of user privacy).

Richard has physical issues, but they do NOT interfere with his use of the device.  If Richard is given access to the editing functions of the device then he typically will accidentally delete something important and get frustrated. 

# Lee
[Lee Ridley](https://en.wikipedia.org/wiki/Lee_Ridley_(comedian)) 

Lee is a professional standup comedy artist who doesn't speak.  He uses a device to quickly trigger pre-programmed lines.  He accesses his device by the touchscreen easily.  He is fully literate and users the programming function extensively.  Response speed  and editor effectiveness are important to lee's use case. 

# Stephen
Stephen has ALS, and accesses his speech device by [switch access scanning](https://en.wikipedia.org/wiki/Switch_access_scanning). He is quite bright.  He also uses his device to trigger pre-programmed lines and it is important to him that both programming and accessing the memory can be done with the minimum amount of scanning.

**Comment by joereddington-public** [comment]
https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/OpenVoiceFactory-Requirements now contains a set of personas. I think the remaining gotchas should arrive as they come up organically. :)
